Updates routing logic
makersacademy/acebook-april2017 pull request #11
Opened 2017-05-30 13:34 UTC by TimRobinson1

Quick update to the routing logic - if the user is currently signed in, root takes you to THE WALL.  Else, it takes you to the signup page.

2017-05-30 13:56 UTC, adamjohnsnow approved these changes
Looks good to me (might want to clean up the home_helper_spec)

2017-05-30 14:04 UTC, neoeno requested changes
There's some docs in here that might have saved you a little work — https://github.com/thoughtbot/clearance ("Clearance also provides routing constraints that can be used to control access at the routing layer:") — but I'll leave that up to you whether you like it or not.

Let's get these unused files out of the way and then we can merge

2017-05-30 14:04 UTC, neoeno commented on spec/controllers/home_controller_spec.rb
> +end
I'd suggest deleting this file

2017-05-30 14:04 UTC, neoeno commented on app/assets/stylesheets/home.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
I'd suggest deleting this file

2017-05-30 14:04 UTC, neoeno commented on app/assets/javascripts/home.js
> +// All this logic will automatically be available in application.js.
I'd suggest deleting this file

2017-05-30 14:29 UTC, TimRobinson1 commented
We added some changes, including using the built in Clearance constraints (thank you, Kay!) and removed the un-needed files.  Users who are not signed in now have no access to posts and must first sign_up/sign_in

2017-05-30 14:54 UTC, neoeno commented
Great! I'd delete home_controller, home_helper, and home_controller_spec. I think I'm right in saying they're no longer required?

2017-05-30 15:03 UTC, TimRobinson1 commented
Right, I've removed those, you're right about them being no longer required.

2017-05-30 15:04 UTC, neoeno requested changes

2017-05-30 15:04 UTC, neoeno commented on app/helpers/home_helper.rb
> +end
One more!

2017-05-30 15:07 UTC, neoeno approved these changes

2017-05-30 15:07 UTC, neoeno commented
Great work!

2017-05-30 21:51 UTC, neoeno commented
(Go ahead and merge when you're ready, btw!)

2017-05-31 09:56 UTC, neoeno approved these changes
Still looks good!

2017-05-31 09:56 UTC, merged