links are converted to urls
makersacademy/acebook-april2017 pull request #12
Opened 2017-05-30 13:51 UTC by Linh91

2017-05-30 14:01 UTC, Achlaw approved these changes
Approve feature "URL are converted to clickable links".

2017-05-30 14:11 UTC, neoeno requested changes
Great work!

I think there's quite a lot of work going on in the views here — probably a good time to extract this stuff to a rails helper method.

2017-05-30 17:07 UTC, baree99 commented
@neoeno I extracted the url creator, can you please have another look?

2017-05-31 10:15 UTC, neoeno approved these changes
Get rid of that `save_and_open_page` and we're good to merge!

2017-05-31 10:15 UTC, neoeno commented on spec/features/newest_posts_first_spec.rb
> +    save_and_open_page
Worth removing this I think

2017-05-31 10:15 UTC, neoeno commented on app/helpers/application_helper.rb
> +  end
Nice — paves the way for future refactors. This could be broken up a little more I'd say but it's good enough to merge now I think.

2017-05-31 10:57 UTC, neoeno approved these changes
Super nice changes!

2017-05-31 10:57 UTC, merged