Design styling forms
makersacademy/acebook-april2017 pull request #15
Opened 2017-05-30 17:31 UTC by sulaimancode

Added custom forms and styled them. Forms can take in additional fields(name) without having to change any css.

2017-05-31 10:28 UTC, motri commented
Text is not as readable as it could be, maybe a change of background color?

2017-05-31 10:30 UTC, motri requested changes
The text is not as readable as it could, lighter font or background colour would help.

2017-05-31 14:08 UTC, motri approved these changes

2017-05-31 15:29 UTC, neoeno requested changes
Nice work. A few comments re: CSS conventions & file organisation.

2017-05-31 15:29 UTC, neoeno commented on app/assets/stylesheets/application.css
> +}
In general when styling it's best to add a class to the element and then use that to target styling — classes for styling, IDs (and sometimes other things) for Javascript targetting.

2017-05-31 15:29 UTC, neoeno commented on app/assets/stylesheets/application.css
> +}
I think this `content` directive doesn't do anything, right?

2017-05-31 15:29 UTC, neoeno commented on app/assets/stylesheets/application.css
> +
A few blank lines here

2017-05-31 15:29 UTC, neoeno commented on app/views/users/new.html.erb
> +      <%= form.text_field :name, :type => 'name', placeholder: 'Name..' %>
I'm a bit of a stickler for detail — but the rest of the fields have `...` and this one has `..` — probably best to stick to 3! There are a few instances of having just 2 throughout I believe?

2017-05-31 15:29 UTC, neoeno commented on app/assets/stylesheets/application.css
> +#new_user {
I'd break this out to another file. `application.css` can grow out of control and become terrible for merge conflicts if you're not careful.

2017-05-31 15:29 UTC, neoeno commented on app/views/sessions/new.html.erb
> +<% end %>
This needs indenting another step.

2017-06-01 02:09 UTC, sulaimancode commented
Made all the required changes. Added an additional scss file for forms styling, used classes to target styling rather than ids, removed unnecessary lines of code and fixed some indentation.

2017-06-01 12:34 UTC, neoeno approved these changes

2017-06-01 12:38 UTC, merged