Comments
makersacademy/acebook-april2017 pull request #16
Opened 2017-05-30 18:12 UTC by BertZZ

Trying to make a new Pull request to get travis to pass

2017-05-30 18:18 UTC, BertZZ commented
Great, Now im getting that error that you were telling me about @henryhobhouse where my test to check that the post is going into the first <p> is failing. Any fix?

2017-05-31 09:58 UTC, TimRobinson1 commented
Don't forget to keep the branch up to date with the master in case of conflicts.

2017-05-31 10:02 UTC, BertZZ commented
Will do. Code looks good though yeah?

2017-05-31 10:09 UTC, TimRobinson1 approved these changes
Looks good to me.  Good edge case test with the empty comment.  I ran your tests and they're passing, just make sure you check again when you update/pull from the master before heading on.

2017-05-31 10:19 UTC, neoeno requested changes
Nice, just a couple small changes.

To make this PR even better I'd add some really basic front-end functionality and a feature test for it. Doesn't have to look pretty, just shove out the comments next to each post. This 'proves' (to yourself mainly, but also to reviewers) that you've built something that will plausibly work for its intended use-case.

Also makes sure it doesn't get forgotten and live in the models doing nothing for years!

(Don't worry about making that change to this PR now though — just advice for the future)

2017-05-31 10:19 UTC, neoeno commented on spec/models/comment_spec.rb
> +  it 'Cannot be empty' do
extra line required before here I'd say

2017-05-31 10:19 UTC, neoeno commented on spec/models/comment_spec.rb
> +    expect(comment.id).not_to be_nil
I think you can say this like:

```ruby
expect(comment).to be_valid
```

2017-05-31 10:44 UTC, neoeno requested changes

2017-05-31 10:44 UTC, neoeno commented on spec/models/comment_spec.rb
> +    expect(comment.id).to be_nil
Sorry, I meant throughout the file! `expect(comment).to_not be_valid`

2017-05-31 10:44 UTC, neoeno commented on spec/models/comment_spec.rb
> +    expect(comment.id).to be_nil
And here

2017-05-31 10:44 UTC, neoeno commented on spec/models/comment_spec.rb
> +    expect(comment.id).to be_nil
And here

2017-05-31 11:24 UTC, neoeno commented
You've added a photo of yourself and of an owl.

2017-05-31 11:27 UTC, BertZZ commented
Dammit!! I was code reviewing the photos form....i'll figure it out

2017-05-31 11:39 UTC, neoeno approved these changes

2017-05-31 11:39 UTC, neoeno commented
Quick, merge it before anyone else merges anything!

2017-05-31 11:43 UTC, merged