Avatar
makersacademy/acebook-april2017 pull request #32
Opened 2017-06-01 15:34 UTC by anthony-crisp

Avatar now shows next to posts and comments.

2017-06-01 15:37 UTC, adamjohnsnow requested changes
See comment to line 25

2017-06-01 15:37 UTC, adamjohnsnow commented on app/views/posts/index.html.erb
> +        <p> <%= image_tag post.user.avatar.to_s, size: User::AVATAR_SIZES[:small] %> <%= comment.user.name %> said: <%= comment.body %></p>
Is this right - should it not be the comment.user.avatar here?

2017-06-01 15:39 UTC, adamjohnsnow approved these changes
Looks good. Over to @neoeno

2017-06-01 17:12 UTC, neoeno commented
Update this to the latest master and you'll have a test failure — a canary in the coal mine for breaking master due to old DB stuff! Have a go at fixing that.

I think it might be nice to somehow modify `User` so that no one can make this mistake again!

2017-06-01 17:18 UTC, neoeno commented
Actually @JayWebDevCom and @sulaimancode just told me they're going to fix the whole issue! So you only need to wait for them to do that.

2017-06-02 11:29 UTC, neoeno commented
@adamjohnsnow or @JayWebDevCom can you confirm this isn't going to cause any issues in production now? Then we can go ahead and merge!

2017-06-02 11:30 UTC, neoeno approved these changes

2017-06-02 12:07 UTC, adamjohnsnow commented
@neoeno The migrations sorted orphaned posts and comments but I don't think this will now work as some users won't have avatars...

2017-06-02 12:30 UTC, neoeno commented
We have default avatars though right?

2017-06-02 12:31 UTC, adamjohnsnow commented
No. I'll get on that now.

2017-06-02 12:56 UTC, neoeno commented
```
2.4.0 :005 > Post.all.first.user.avatar.to_s
  Post Load (0.5ms)  SELECT  "posts".* FROM "posts" ORDER BY "posts"."id" ASC LIMIT $1  [["LIMIT", 1]]
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
 => ""
```

No errors on the web interface either! I say merge.

2017-06-02 13:06 UTC, merged