Repositions and styles 'new posts' button
makersacademy/acebook-april2017 pull request #49
Opened 2017-06-02 12:01 UTC by itsalwaysbenny

'New posts' link now appears in a fixed position beneath the nav bar at the top of the page. Changes colour upon mouse hover.

2017-06-02 12:06 UTC, BertZZ requested changes
Looks fine to me however you seem to have some failing Rspec tests. It seems like you have broken the Routing so maybe @TimRobinson1 is the perfect person to check this out

2017-06-02 12:06 UTC, BertZZ commented on app/views/posts/index.html.erb
> +
Why are these 2 lines here?

2017-06-02 13:14 UTC, bruxelles86 commented on app/views/posts/index.html.erb
> +
Deleted

2017-06-02 13:15 UTC, bruxelles86 commented
@BertZZ I've fixed the failing tests, which were checking that the button *doesn't* appear when you're not logged in.

2017-06-02 13:38 UTC, BertZZ commented
Cool beans. Send it to @neoeno for a look

2017-06-02 15:08 UTC, BertZZ approved these changes

2017-06-02 18:53 UTC, neoeno requested changes
Nice work! Just a few small comments

2017-06-02 18:53 UTC, neoeno commented on app/assets/stylesheets/application.css.scss
> +}
I'd probably move these classes to their own file — `application.css` can often grow out of control if it is added to often! Maybe `navigation.css`, or something similar.

2017-06-02 18:53 UTC, neoeno commented on app/views/layouts/application.html.erb
> +  </div>
I'd like to see this diff be just lines 30-32 — the whitespace and formatting changes seem to add churn without benefit.

2017-06-02 18:53 UTC, neoeno commented on app/views/layouts/application.html.erb
> +    <% end %>
Nice, I like this `link_to do` syntax!

2017-06-02 22:29 UTC, bruxelles86 commented
@neoeno - thanks for the review! Have extracted the CSS as you suggested, and also *tried* to reformat the changes to layout so the change is limited to lines 30-32. Hope it's OK.

2017-06-03 14:51 UTC, neoeno approved these changes

2017-06-03 14:52 UTC, neoeno commented
Looks good! Great work here!

2017-06-03 15:23 UTC, BertZZ commented
I think I might have accidently broke this, Looks like Ill have to try fix it

2017-06-03 15:33 UTC, merged