Dynamic like v3 kay diversion
makersacademy/acebook-april2017 pull request #53
Opened 2017-06-02 18:21 UTC by henryhobhouse

Altered JS to allow post submit on Like to allow server side update

2017-06-02 19:02 UTC, neoeno requested changes
Some great work here! I'm really tempted to just say go ahead but I know I'd be failing you if I didn't give you some feedback to go away with!

2017-06-02 19:02 UTC, neoeno commented on app/assets/stylesheets/likes.scss
> +  // box-shadow: 0 0 10px #fff;
Commented out code

2017-06-02 19:02 UTC, neoeno commented on app/assets/javascripts/likes.js
> +}
I'd extract the `ready` function to another file and use rails require comments to require it first in `application.js`. That way we won't have it repeated in `avatar.js` and `likes.js`.

Bear in mind you'll need to test the avatar fnality too to make sure it works!

2017-06-03 14:26 UTC, neoeno approved these changes
Love this change! Great to see the refactor getting combined with refactoring another feature — nice work!

2017-06-03 15:45 UTC, BertZZ commented
@henryhobhouse want to resolve these conflicts?

2017-06-04 09:44 UTC, henryhobhouse commented
Update again to finally work with new method to split out the different onload functions in their relative locations so defunct JS isn't constantly being called. Updated so the quotes are working; presumably broken from another update from Tim and Issy's work?

2017-06-04 12:19 UTC, merged