refactored following hounds reccomendations
makersacademy/acebook-april2017 pull request #6
Opened 2017-05-29 18:50 UTC by henryhobhouse

By-passed clearance gem default routing and created new form view. Updated db schema to have name added into user model. Validates name required in user model file. Accidentally pushed to master after updating git folder and forgetting to switch back to branch. Fail!!!

2017-05-30 12:36 UTC, neoeno commented on spec/models/user_spec.rb
> +  it "it is not valid without a password" do
You can ignore this — hound is using the wrong config

2017-05-30 15:50 UTC, BertZZ commented
Worried this is going to upset the front end. Is this going to conflict with the forms @sulaimancode and @TimRobinson1 were working on today?

2017-05-30 15:52 UTC, BertZZ commented
Also if anyone checks out this branch you will have to drop and re create/migrate your tables

2017-05-30 16:46 UTC, TimRobinson1 approved these changes
I've had a look over it and I can't see that anything here is an issue.  I particularly like the number of tests you've got going on.  This setting up of the user name incorporated into the user should work nicely with the forms we're creating.

2017-05-30 16:52 UTC, neoeno requested changes

2017-05-30 16:52 UTC, neoeno commented on db/migrate/20170528155838_create_users.rb
> +      t.string :name, null: false, limit: 50
> In general, editing existing migrations is not a good idea. You will be creating extra work for yourself and your co-workers and cause major headaches if the existing version of the migration has already been run on production machines. Instead, you should write a new migration that performs the changes you require. Editing a freshly generated migration that has not yet been committed to source control (or, more generally, which has not been propagated beyond your development machine) is relatively harmless.

http://edgeguides.rubyonrails.org/active_record_migrations.html#changing-existing-migrations

2017-05-30 16:52 UTC, neoeno commented on config/routes.rb
> +    only: 'create'
Personally I'd have this on one line, since it's only short, but it's not a big deal.

2017-05-30 16:52 UTC, neoeno commented on app/views/users/new.html.erb
> +  <% end %>
I'd indent everything inside this `form_for` (I guess the code comes from elsewhere — but still good to make it conform)

2017-05-30 16:52 UTC, neoeno commented on app/models/user.rb
> +  validates :name, presence: true
Can we get a test for `tries with an invalid name` to go with the ones for invalid email/username?

2017-05-31 08:53 UTC, henryhobhouse commented on db/migrate/20170528155838_create_users.rb
> +      t.string :name, null: false, limit: 50
Morning Kay, this is done. Took some time to learn how but glad I did.

2017-05-31 08:56 UTC, henryhobhouse commented on app/models/user.rb
> +  validates :name, presence: true
Added test to confirm this doesn't work

2017-05-31 09:55 UTC, neoeno commented on db/migrate/20170528155838_create_users.rb
> +      t.string :name, null: false, limit: 50
@henryhobhouse Is it pushed? I don't see any changes!

2017-05-31 09:59 UTC, henryhobhouse commented on app/views/users/new.html.erb
> +  <% end %>
How very rude to correctly assume the code comes from elsewhere ;) Now indented.

2017-05-31 10:09 UTC, neoeno approved these changes
Looks good when that file/migration naming change is made. Go ahead and merge after that!

2017-05-31 10:09 UTC, neoeno commented on db/migrate/20170531081508_add_nameto_users.rb
> +class AddNametoUsers < ActiveRecord::Migration[5.1]
Just a small thing — this should be `AddNameToUsers` and the file named `add_name_to_users`

2017-05-31 10:14 UTC, henryhobhouse commented on db/migrate/20170531081508_add_nameto_users.rb
> +class AddNametoUsers < ActiveRecord::Migration[5.1]
Thanks. Updated will pull in master now and push once tests are passed.

2017-05-31 10:50 UTC, merged